### ISSUE TITLE
写的很好，在下十分钦佩，现有些问题要请教作者一番

### ISSUE THREAD

**Issue by tomatowithpotato** [josexy/socnet-cpp#1]
本人新手，绝的作者的代码写的很棒，模块清晰，功能齐全，非常适合新人阅读
现有些疑问想向您请教一番

1. 不知该项目后续是否还会更新？
2. 目前似乎不支持chunked分块传输，不知道以后会不会支持？
3. 目前好像没有检查请求体内容是否接收完整，这是为什么呢？其实至少能够通过检查content-length字段来做判断的吧？
4. 之前没接触过https，如果要写https的话是不是要自己搞个网站证书才能使用呢？

问的有点多，如能获回复，感激不尽

**Comment by josexy** [comment]
1. 该项目可能很长一段时间不会更新了
2. 分块传输目前暂时没有支持的想法
3.

**Comment by josexy** [comment]
共勉～😁
1. 该项目可能很长时间不会更新了
2. 目前还暂时没有这个想法
3. 该web服务器解析请求体内容只支持 application/x-www-form-urlencoded 和 multipart/form-data 这两种基本类型（对应代码 [HttpRequest::parseRequestContent](https://github.com/josexy/socnet-cpp/blob/b104ede911c0a2ff90e2348ad2b6647e4a565b36/soc/http/src/HttpRequest.cc#L182) ），正常情况下解析不会出现错误，因此可以不必检查content-length字段
4. 证书可以本地用openssl生成，或者可以到这个网站申请证书 https://letsencrypt.osfipin.com/
